version: '3.8'

services:
  backend:
    build:
      context: .
    container_name: simulador-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/simulador
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - "8080:8080"
    networks:
      - db-net

  db:
    image: postgres:15
    container_name: simulador-db
    environment:
      POSTGRES_DB: simulador
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - db-net

volumes:
  pgdata:

networks:
  db-net:
