
spring.datasource.url=jdbc:postgresql://localhost:5432/imc
spring.datasource.username=user
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
