name: Deploy Node + SpringBoot to AWS EC2

on:
  push:
    branches: [Pratica03]

jobs:

  deploy-backend:
    name: Deploy Backend + Postgres
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Verificar se SSH_PRIVATE_KEY está disponível
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | head -n 2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Build backend JAR
      run: |
        cd simulador_emprestimo_back
        mvn clean package -DskipTests
        cd ..

    - name: Apagar e copiar arquivos do backend para EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.AWS_BACKEND_HOST }} "rm -rf ~/app-backend"
        scp -r -o StrictHostKeyChecking=no simulador_emprestimo_back ${{ secrets.EC2_USER }}@${{ secrets.AWS_BACKEND_HOST }}:/home/${{ secrets.EC2_USER }}/app-backend

    - name: Subir backend + Postgres na EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.AWS_BACKEND_HOST }} << 'EOF'
          sudo apt update
          cd ~/app-backend
          docker compose down || true
          docker compose up -d --build
        EOF

  deploy-frontend:
    name: Deploy Frontend Node.js
    runs-on: ubuntu-latest
    needs: deploy-backend

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Apagar e copiar frontend para EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.AWS_FRONTEND_HOST }} "rm -rf ~/app-frontend"
        scp -r -o StrictHostKeyChecking=no simulador_emprestimo_front ${{ secrets.EC2_USER }}@${{ secrets.AWS_FRONTEND_HOST }}:/home/${{ secrets.EC2_USER }}/app-frontend

    - name: Subir frontend na EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.AWS_FRONTEND_HOST }} << 'EOF'
          sudo apt update
          cd ~/app-frontend
          docker compose down || true
          docker compose up -d --build
        EOF
